"""empty message

Revision ID: 31cc48533301
Revises: e8da52b1a8ea
Create Date: 2016-02-27 03:50:46.865301

"""

# revision identifiers, used by Alembic.
revision = '31cc48533301'
down_revision = 'e8da52b1a8ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
