"""empty message

Revision ID: 69419b30e926
Revises: ac994e25e3cd
Create Date: 2016-03-12 19:59:31.041822

"""

# revision identifiers, used by Alembic.
revision = '69419b30e926'
down_revision = 'ac994e25e3cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'body')
    ### end Alembic commands ###
