"""empty message

Revision ID: da723f0ffe31
Revises: 69419b30e926
Create Date: 2016-03-20 03:00:04.704687

"""

# revision identifiers, used by Alembic.
revision = 'da723f0ffe31'
down_revision = '69419b30e926'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(u'ix_social_email', 'social', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_social_email', table_name='social')
    op.drop_table('social')
    ### end Alembic commands ###
